namespace Grand.Business.Core.Utilities.System;

/// <summary>
///     Represents a category revenue report line
/// </summary>
public class CategoryRevenueReportLine
{
    /// <summary>
    ///     Gets or sets the category identifier
    /// </summary>
    public string CategoryId { get; set; }

    /// <summary>
    ///     Gets or sets the total revenue generated by the category.
    ///     Uses double to match the existing codebase convention for monetary report aggregations.
    /// </summary>
    public double TotalRevenue { get; set; }

    /// <summary>
    ///     Gets or sets the total number of orders containing products from the category
    /// </summary>
    public int TotalOrders { get; set; }
}
