namespace Grand.Business.Core.Utilities.System;

/// <summary>
///     Represents a vendor performance report line
/// </summary>
public class VendorPerformanceReportLine
{
    /// <summary>
    ///     Gets or sets the vendor identifier
    /// </summary>
    public string VendorId { get; set; }

    /// <summary>
    ///     Gets or sets the total revenue generated by the vendor
    /// </summary>
    public double TotalRevenue { get; set; }

    /// <summary>
    ///     Gets or sets the total number of orders fulfilled by the vendor
    /// </summary>
    public int TotalOrders { get; set; }

    /// <summary>
    ///     Gets or sets the average value of orders fulfilled by the vendor
    /// </summary>
    public double AverageOrderValue { get; set; }
}
